import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
import { JvmInterceptor } from '../../../src/interceptors/jvm-interceptor.js';
const source=fs.readFileSync(new URL('../../../src/ui/app.js',import.meta.url),'utf8');
const section=(start,end)=>source.slice(source.indexOf(start),source.indexOf(end,source.indexOf(start)));
test('uncertain JVMs remain visible for cleanup but are not connected or confirmed active',()=>{
 const jvm=new JvmInterceptor();jvm.active=true;
 jvm.activatedProcesses.set('123',{name:'Uncertain',activationUncertain:true});
 const context=vm.createContext({expandedInterceptorMetadata:{processes:[],activatedProcesses:jvm._getActivatedProcessMetadata()},esc:value=>String(value??'')});
 vm.runInContext(section('function renderJvmConfig(', 'async function activateJvmProcess(')+section('function isConnectedInterceptorSource(', 'function updateAndroidInterceptorFromMetadata('),context);
 assert.equal(context.isConnectedInterceptorSource(jvm.toJSON()),false);
 const container={innerHTML:''};context.renderJvmConfig(container);
 assert.match(container.innerHTML,/Uncertain/);
 assert.match(container.innerHTML,/Activation uncertain/);
 assert.match(container.innerHTML,/Stop and clean up all JVM attachments/);
 assert.doesNotMatch(container.innerHTML,/pill-active|>Attach<|>Activated</);
 jvm.activatedProcesses.set('456',{name:'Confirmed'});
 assert.equal(context.isConnectedInterceptorSource(jvm.toJSON()),true);
 context.expandedInterceptorMetadata.activatedProcesses=jvm._getActivatedProcessMetadata();
 context.renderJvmConfig(container);
 assert.equal((container.innerHTML.match(/>Activated</g)||[]).length,1);
 assert.equal((container.innerHTML.match(/>Activation uncertain</g)||[]).length,1);
 jvm.activatedProcesses.delete('123');
 context.expandedInterceptorMetadata.activatedProcesses=jvm._getActivatedProcessMetadata();
 context.renderJvmConfig(container);
 assert.doesNotMatch(container.innerHTML,/Activation uncertain|Stop and clean up/);
 assert.equal(jvm.toJSON().activationUncertain,false);
});
